apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Khanhle11342/Khanh-aws-accelerator-p2.git
    targetRevision: main
    path: modules/apps/web

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
